### ISSUE TITLE
UncompressedSize() is not bytes

### ISSUE THREAD

**Issue by TimDykes** [ugovaretto/tjpp#6]
In JPEGImage.h:

The UncompressedSize() function returns the number of components per pixel \* number of pixels.

To be consistent with JPEGSize() it should be number of components per pixel \* number of pixels \* sizeof(pixel component), where in this case pixel component is float32. 

It may simply be a case of multiplying by 4, as I dont see any capability in tjpp for non float32 based images, but in case supporting that is planned for future perhaps it needs a more clever approach. (I didnt check whether lib turbo jpeg supports non-float images, i guess if it doesnt then the answer is simply multiply by 4 appropriately in the UncompressedSize() function)

**Comment by ugovaretto** [comment]
? there is no float32 type anywhere to my knowledge: e.g. a three component

The only understood format is one byte per component: the buffer passed to the compressor and decompressor must be an array of bytes and contain images with 1, 3 or 4 bytes per pixel

TJPF_RGB=0,
  /**
- BGR pixel format.  **The red, green, and blue components in the image are
- stored in 3-byte pixels*\* in the order B, G, R from lowest to highest byte
- address within each pixel.
  */

**Comment by TimDykes** [comment]
Oh, this isnt an issue then, I was under the assumption the pixel formats were floating point..
