### ISSUE TITLE
JPEGImage reset() doesnt update jpegSize_

### ISSUE THREAD

**Issue by TimDykes** [ugovaretto/tjpp#7]
At the end of reset() you should insert the following line so that the size is reported correctly by JPEGSize()

jpegSize_ = sz;

**Comment by TimDykes** [comment]
This sets jpegSize_ to the max size of the tjBuffer, may want to be along the lines of w \* h \* NumComponents(pf) \* sizeof(component) instead?

**Comment by TimDykes** [comment]
Actually that would set jpegSize_ to UncompressedSize, which is wrong. So perhaps its not necessary to set jpegSize_ in reset() - however I am leaving the issue open because JPEGSize() will report incorrectly after a reset(), so something should be done in any case..

**Comment by ugovaretto** [comment]
The right way is actually to set the max jpeg size through the tjBufSize() call, but that's exactly what we need to discuss because it has other implications especially when using move semantics.

**Comment by ugovaretto** [comment]
We should close this right ?

**Comment by TimDykes** [comment]
Yes - reset() now sets BufferSize and CompressedSize to tjBufSize()
