### ISSUE TITLE
colorspace != pixel format

### ISSUE THREAD

**Issue by TimDykes** [ugovaretto/tjpp#9]
In TjDeCompressor.h we call:

```
    tjDecompressHeader3(tjDeCompressor_,
                           jpgImg,
                           size,
                           &width,
                           &height,
                           &jpegSubsamp,
                           &colorSpace))
```

then later call:

```
    if(tjDecompress2(tjDeCompressor_, jpgImg, size, img_.DataPtr(),
                     width, pitch, height, colorSpace, flags))
```

The problem is that a turbo jpeg colorspace (TJCS) is not the same as a turbo jpeg pixel format (TJPF). The TJCS (colorSpace) returned by tjDecompressHeader3 cannot be passed as a TJPF to tjDecompress2.

It seems the pixel format isnt actually stored in the header, or at least isnt exposed by tjDecompressHeader3 and there seems to be no other header related functions. This means you must know the pixel format in advance and pass it directly to the Decompress() function along with the data pointer, size, flags and pitch. 

( For TJCS vs TCPF: https://cdn.rawgit.com/libjpeg-turbo/libjpeg-turbo/master/doc/html/group___turbo_j_p_e_g.html#ga4f83ad3368e0e29d1957be0efa7c3720 )

**Comment by ugovaretto** [comment]
We should be just using tjDecompressHeader2 and forget about the colorspace as it was the case in the original version, this thing was added as an experiment, however it really seems this thing is not used at all  in decompress2.
Or we just avoid reading from the header all together and trust the width/height passed from client code.

**Comment by TimDykes** [comment]
Well that's what I assumed at first, but the api documentation only seems to detail Tjdecompressheader3 - there's no '2. Is this just an accidental omission from the api docs?

**Comment by TimDykes** [comment]
I assume it must be, its clearly in turbojpeg.h, ill swap to that - I like the idea of reading the header as they will clearly be the right values, reducing chances of mistakes. In fact I think it would be better just to remove the extra arguments to Decompress()... 

(edit: i realise now there arent extra arguments anyway! ignore the last sentence)

**Comment by ugovaretto** [comment]
The *3 version was added in v1.5 I believe, but either way we can keep it as it is but avoid passing the colorSpace we read to decompress, although I do not even know if they use this information at all, it seems that the relevant one is the subsampling value.

**Comment by TimDykes** [comment]
Actually I think we have to use the *2 version, as this can extract the pixel format from the header which is necessary for decompression. 

What I intended to do was replace the *3 version with *2, extract all the colorspace related stuff into colorspace.h, and replace the colorspace stuff in Image.h with TJPF as in JPEGImage (because the colorspace stuff is wrong anyway, so it shouldn't really be included)

**Comment by TimDykes** [comment]
In fact I was looking at the wrong function, we still have to provide the pixel format manually. But in any case it is better to replace with *2 so I can extract the incorrect colorspace stuff
